### ISSUE TITLE
Incorrect installation of plugin for Ionic 3

### ISSUE THREAD

**Issue by muhammad-omar** [Instabug/instabug-cordova#101]
While trying different options to install the plugin to Ionic 3 project, i keep getting to the same version "8.0.4" of the plugin and that causes some build issues.

tried options: 
"ionic cordova plugin add instabug-cordova@latest --save"
"ionic cordova plugin add instabug-cordova --save" 
"ionic cordova plugin add instabug-cordova@9.1.0 --save"
"cordova plugin add instabug-cordova@latest --save"
"cordova plugin add instabug-cordova --save" 
"cordova plugin add instabug-cordova@9.1.0 --save"

but all results in the same version of the plugin being installed "8.0.4" even though i can see that recent version has the version bump merged.

also tried "npm cache clear --force" but no luck

**Comment by alyezz** [comment]
@muhammad-omar we are aware of this issue, we did not update the version inside `plugin.xml` that's why you see the same version number, however, its updated inside the `package.json` file.

Sorry for the inconvenience, we will make sure to update the `plugin.xml` in future releases.
