### ISSUE TITLE
bugReporting invocationEvents not working 

### ISSUE THREAD

**Issue by tamsel12** [Instabug/instabug-cordova#103]
invocation event  often opens the "Need Help" popup. I added it for the shake event only, but it shows oftentimes with latest plugin only. If document has updated, please let us know here. Thanks in advance

**Comment by alyezz** [comment]
@tamsel12 i'm not sure i understand what you mean exactly, can you please elaborate?

**Comment by tamsel12** [comment]
After opening the app itself i am getting the popup [Which will show only after the shake event]  oftentimes. My app targets Api level 29 and it is latest cordova plugin only

**Comment by alyezz** [comment]
@tamsel12 which popup are you referring to? can you attach a screenshot?

**Comment by tamsel12** [comment]
Okay, This popup is showing often times https://user-images.githubusercontent.com/45559546/87543926-33e83600-c6c3-11ea-9de0-199f4d9e4ad6.jpg @alyezz

**Comment by alyezz** [comment]
@tamsel12 you can try changing the shaking threshold https://docs.instabug.com/docs/cordova-invocation#shaking-threshold

**Comment by tamsel12** [comment]
I have integrated the same code which is mentioned in document @alyezz . It has worked 100% in version 8.6.5, after upgrading 9.1.0 only i am getting this issue. My App is built using ionic 3 and now migrating to Android Api level 29.

**Comment by alyezz** [comment]
@tamsel12 i see, however the case where the device shows the prompt is usually because it detected a shake, so changing the shaking threshold using the above link from our docs might solve your issue. Can you please try that and let me know?

**Comment by tamsel12** [comment]
I have removed instabug activate method for android and updated the token in  MainApplication file. Now Its working fine, Before i have used 8.6.5 version which did not have myApplicaiton Class inside in android src , so  i added instabug activate method. But now removing that code works fine in the latest release of the cordova plugin versioin. Thanks :)
