### ISSUE TITLE
Header overlays app buttons

### ISSUE THREAD

**Issue by Bart1909** [Instabug/Instabug-Cordova#136]
When sending an improvement or reporting a bug, the header (with its buttons to send or cancel the improvement/bug) is overlaying the header of the app:
![image](https://user-images.githubusercontent.com/14097923/165038916-c2230e1f-47ae-47a2-8569-8a947a8acb81.png)

![image](https://user-images.githubusercontent.com/14097923/165038999-ec872812-cf00-4673-92ee-a7c2d297eef1.png)

**Comment by AliAbdelfattah** [comment]
Hey @Bart1909, sorry for the late reply, we weren't able to reproduce this behavior on our end. However, we've recently released a new version, could you give it a try on that?

**Comment by AliAbdelfattah** [comment]
Closing the issue since we haven't heard back from you. Please feel free to reopen the issue if you have more information to add.
