### ISSUE TITLE
Set Primary Color

### ISSUE THREAD

**Issue by xueligoh** [Instabug/Instabug-Cordova#157]
There is a typo for setting primary color

Instabug.setPrimaryColor = function (`color`, success, error) {
    exec(success, error, 'IBGPlugin', 'setPrimaryColor', [`colorInteger`]);
};

**Comment by DavidMina96** [comment]
Thank you for reporting this, @xueligoh! It'll be fixed in our next release, and here's a snapshot with the fix as well:
`cordova plugin add https://github.com/Instabug/Instabug-Cordova\#snapshot/11.0.0-MOB-9117`

**Comment by DavidMina96** [comment]
@xueligoh The fix is now included in v11.0.1 🚀
