### ISSUE TITLE
Instabug interferes with Camera plugin

### ISSUE THREAD

**Issue by xueligoh** [Instabug/Instabug-Cordova#159]
hi instabug team, 

we find that when we include instabug into our application, our camera plugin stops working (camera cannot be launch). is there something in instabug implementation that interferes with the camera plugin?

**Comment by DavidMina96** [comment]
Hi @xueligoh, 

Thank you for reporting this. Could you please provide us with more information regarding the installed versions of `cordova`, `cordova-android`, `cordova-ios` and `cordova-plugin-camera` and whether you are facing the issue on a specific platform or device? 

While it's not required, including a sample project that reproduces the issue will be of help.

**Comment by xueligoh** [comment]
Hello!

We see this issue on Android - the camera works when we exclude instabug from the build, but when we include instabug, the camera will not launch. select from gallery works well.

I am using camera plugin 5.0.3 with the instabug v11.0.0 

<img width="407" alt="Screenshot 2022-07-27 at 10 21 27 PM" src="https://user-images.githubusercontent.com/24445307/181271366-19a77fcf-a29b-4c74-94f9-fd898dbacb37.png">

I do not have a sample project at the moment as we are using a platform for this and the build is generated from the platform. I will see if I can do up a separate project locally but would appreciate if you can have a look as well, thank you!

**Comment by DavidMina96** [comment]
Thank you for providing these details, @xueligoh! We were able to reproduce the issue of camera not launching on `cordova-plugin-camera` v5.0.3, but it works well on the latest version 6.0.0. Would you please give it a try on the latest version, along with Instabug, and let us know if it resolves the issue?

**Comment by xueligoh** [comment]
Hi @DavidMina96 it did not work for us sadly.

**Comment by DavidMina96** [comment]
@xueligoh Since the issue is not reproducible on our side on the latest version, we will be waiting for a sample project that reproduces the issue whenever possible so that we can further look into it.

**Comment by xueligoh** [comment]
Hi @DavidMina96 

Please find the attached project & the build that we tried in this URL (unable to upload more than 25 MB here)
https://drive.google.com/drive/folders/19BWJMy7oGTJr2ATHzwG86ZT0fQSMltR_?usp=sharing

**Comment by xueligoh** [comment]
Hi @DavidMina96 

Apologies for asking so soon. Have you had the chance to take a look at the uploads?

**Comment by DavidMina96** [comment]
Hi @xueligoh,

Thanks for sharing a sample project and the build file. Yes, I've installed the APK and found that upon app launch, the camera launches successfully (after granting permission for the first time), and Instabug prompt options menu appears as well. I was able to get the 'Success' alert, followed by the 'Success camera' alert upon capturing an image and selecting OK. 


Therefore, the issue is still not reproducible on our side. Could you please clarify if there's a different reproduction scenario that you try at your end? Happy to help further with this one :)

**Comment by xueligoh** [comment]
Hi @DavidMina96 
Thanks for following up, we look around further and found that we were actually facing the same issue as https://github.com/Instabug/Instabug-Android/issues/386

After we did the modification to the android manifest, the camera is able to launch.

**Comment by DavidMina96** [comment]
Glad you've figured it out, @xueligoh! The key difference here was in the Android version as we were testing on a device running a lower API level on our side than the one this issue first appeared on. I'm delighted that it's now working as expected for you. 🚀
