### ISSUE TITLE
Add support for Crosswalk Webview

### ISSUE THREAD

**Issue by seljabali** [Instabug/instabug-cordova#16]
I am using `instabug-cordova#v1.1.0` and am getting a blank screen in capturing an image after having done the shake gesture. I'm too using `cordova-plugin-crosswalk-webview 2.0.0` "Crosswalk WebView Engine" library that may or may not be causing this. 

![screenshot_20170324-125607_1024](https://cloud.githubusercontent.com/assets/1254921/24432760/1e0ef832-13d9-11e7-8a41-ce8a72498ee6.png)

**Comment by DevHossamHassan** [comment]
Hello seljabali,
Thank you for reporting this issue, 
It would be great if you can provide us a sample app with its source code contains the issue to help us investigate into that as soon as possible.
I have one more question, Does it happen on all devices or on a specific device?

**Comment by seljabali** [comment]
Hi @DevHossamHassan, 

I've created a repo that reproduces the issue here: https://github.com/travelbank/instabug_bug. 
I've found the issue to be amongst all devices & emulators that I've tried.

Best,
-Sami

**Comment by seljabali** [comment]
Hi @DevHossamHassan, 

Is there an update on this issue? Were you able to reproduce it?

Thanks,
-Sami

**Comment by DevHossamHassan** [comment]
Hey @seljabali, 
We are currently working on it, Yes I did. Thank you so much, I really appreciate that it helped me a lot figuring out the main problem.

After I looked into the sample app that you sent me I figured out that 
Our plugin works fine with android system Webview 
But It doesn't work with `Crosswalk` Webview 
So, we are investigating into it and we will support capturing the `Crosswalk` Webview ASAP
Regards

**Comment by salmatarzi** [comment]
I am going to change the name of this issue to be more relevant to the problem.

**Comment by dherby** [comment]
Still no news on this issue ?

**Comment by reemalashry1** [comment]
Hello @seljabali @dherby 

We need to support `Crosswalk` on the native Android SDK first, I've communicated this to our product team and will post an update here whenever it's added.

**Comment by dherby** [comment]
@reemalashry1 We have been waiting for this fix for a very long time since. Hope you will be able to speed up the fix. Cheers

**Comment by reemalashry1** [comment]
@dherby I'll be checking this with our Android team, will keep you updated, sorry if this is blocking your workflow!

**Comment by dherby** [comment]
@reemalashry1 thanks. I hope you will find a solution. Our app had been downloaded more than 1 million times for Android. We were thinking to put your chat module but quite complicated when crosswalk not working properly. Cheers.

**Comment by dherby** [comment]
@reemalashry1 any news ?

**Comment by ZiadAyman** [comment]
@dherby @seljabali Apologies for the long time that has been taken to reply on this.

We understand that supporting `Crosswalk` is a priority for you currently and we are definitely taking this into consideration.
We have added it to our bakclog, however our backlog is really tight right now. it will take sometime to be honest, no clear dates are promised until now.

I will keep this issue opened, and will get back to you once I have updates regarding it :)

**Comment by seljabali** [comment]
@ZiadAyman, thanks for getting back. We've actually stopped using Crosswalk as it is [deprecated](https://crosswalk-project.org/blog/crosswalk-final-release.html). We've found web pages acting more or less fine without it; heads up to @dherby.

**Comment by ZiadAyman** [comment]
@seljabali Thanks for providing such info :)

Apologies one more time for the response delay from our side. 
I will close this issue for now and I'll keep you posted if I have any Cordova related updates.
