### ISSUE TITLE
Wrong import in IBGPlugin.h when building iOS app with Capacitor

### ISSUE THREAD

**Issue by aginvlad** [Instabug/Instabug-Cordova#160]
Hi team,
After upgrading instabug-cordova to 11.0.0, we couldn't build iOS app in Xcode using Capacitor (we currently use Capacitor 4). The error is the following:

![image](https://user-images.githubusercontent.com/38836906/185608365-11d87269-cbec-4e18-984a-0e795cc1c94f.png)

The files within the folder are the following:

![image](https://user-images.githubusercontent.com/38836906/185608570-16ab4ef4-307e-443c-bca1-0bf23af6fe79.png)

After changing the import to `'./ArgsRegistry.h'` we were able to build the app successfully.

![image](https://user-images.githubusercontent.com/38836906/185609445-c6113015-6ac3-4748-ac8d-b17a9c645a18.png)

Maybe you could take a look at this. Thanks!

**Comment by TheBuggedYRN** [comment]
Thanks @aginvlad for reporting this!
We are looking into it and we will get back to you.

**Comment by TheBuggedYRN** [comment]
@aginvlad This fix is now released in v11.0.1 🎉
