### ISSUE TITLE
Crashes on Android

### ISSUE THREAD

**Issue by solarsaturn9** [Instabug/instabug-cordova#17]
I followed installation and initialization very carefully but I'm still experiencing crashes instantly on Galaxy Note 4 running OS version 5.1.1. Please advise.

**Comment by marijnroukens** [comment]
+1

**Comment by nintra** [comment]
same here. v1.0.0 and probably v1.1.0 (version code is wrong) 
It crashes instantly. No reports were sent. Galaxy S6 with Android 7

**Comment by nintra** [comment]
after upgrading my app was crashing too. It was because `shakingThresholdAndroid` now only accepts integer values. In older versions of this plugin floats where required. So I just changed it to '11' or something higher and it works. ('11' is to sensitive)
