### ISSUE TITLE
Warnings returned during build process

### ISSUE THREAD

**Issue by sunilshenoy** [Instabug/instabug-cordova#18]
/Users/www/platforms/ios/Self/Plugins/com.instabug.cordova.plugin/IBGPlugin.m:268:16: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
        IBGLog(log);
               ^~~
/Users/www/platforms/ios/Self/Plugins/com.instabug.cordova.plugin/IBGPlugin.m:268:16: note: treat the string as an argument to avoid this
        IBGLog(log);
               ^
               @"%@",
/Users/www/platforms/ios/Self/Plugins/com.instabug.cordova.plugin/IBGPlugin.m:364:19: warning: 'setDefaultInvocationMode:' is deprecated: Starting from v6.0, use setPromptOptionsEnabledWithBug:feedback:chat: instead [-Wdeprecated-declarations]
        [Instabug setDefaultInvocationMode:iMode];
                  ^
In module 'Instabug' imported from /Users/www/platforms/ios/Self/Plugins/com.instabug.cordova.plugin/IBGPlugin.m:2:
Self/Plugins/com.instabug.cordova.plugin/Instabug.framework/Headers/Instabug.h:319:1: note: 'setDefaultInvocationMode:' has been explicitly marked deprecated here
+ (void)setDefaultInvocationMode:(IBGInvocationMode)invocationMode DEPRECATED_MSG_ATTRIBUTE("Starting from v6.0, use setPromptOptionsEnabledWithBug:feedback:chat: instead");
^
2 warnings generated.
---------
I have the latest version of the plugin installed and get these error messages after I run the "ionic build ios" command.

**Comment by salmatarzi** [comment]
Hi there @sunilshenoy, is this problem still persistent? If it is, could you please tell me what version of instabug-cordova plugin are you using?

**Comment by salmatarzi** [comment]
I will close this issue for now, if the problem still persists, please re open.
