### ISSUE TITLE
Not able to install using CLI  with commant 'ionic cordova plugin add https://github.com/Instabug/instabug-cordova'

### ISSUE THREAD

**Issue by pintlab** [Instabug/instabug-cordova#24]

**Comment by Slavrix** [comment]
The error tells you what you need to do 

> npm ERR! not found: git
> npm ERR!
> npm ERR! Failed using git.
> npm ERR! This is most likely not a problem with npm itself.
> npm ERR! Please check if you have git installed and in your PATH.

**Comment by salmatarzi** [comment]
@pintlab Did you manage to fix the problem that you had, or is it still there?
