### ISSUE TITLE
DuplicateFileException when packaging android app with cordova

### ISSUE THREAD

**Issue by Slavrix** [Instabug/instabug-cordova#26]
When installing this it was working, then I started getting this exception after updating to cordova-android@6.2.3

When rolling back to cordova-android@6.1.1 this problem remained.

When I removed this plugin it built fin. When I added it back in (using `cordova plugin add https://github.com/Instabug/instabug-cordova -nofetch`) it wouldn't build again and this error showed up again.

```
* What went wrong:
Execution failed for task ':transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate file
s copied in APK META-INF/rxjava.properties
        File1: /Users/admin/Desktop/Gravity/clubezy-meteorionic/platforms/android/build/intermediates/exploded-aar/com.goo
gle.android.gms/play-services-basement/11.0.0/jars/classes.jar
        File2: /Users/admin/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.1.9/e4362e62f1ba92e360b197d6d7ffae67e
5ecae9a/rxjava-1.1.9.jar
```

**Comment by DevHossamHassan** [comment]
Hello @Slavrix,
Thank you for the details that you provided  here, we'll look  into it and will get back to you as soon as possible.

**Comment by Slavrix** [comment]
Ley me know if there is any more info that will help you out, ill try to
get it to you.

**Comment by Slavrix** [comment]
I found that changing the build.gradle file to have this allowed it to build.

```
android {
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    defaultConfig {
        applicationId = doExtractStringFromManifest("package")
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/rxjava.properties'
    }
}
```
