### ISSUE TITLE
cant find where to add my token on android

### ISSUE THREAD

**Issue by garyocampo** [Instabug/instabug-cordova#29]
"add your app token in the MyApplication class, by replacing YOUR_ANDROID_TOKEN by your app token."
where is this?

**Comment by salmatarzi** [comment]
Hello @garyocampo, you can find this class under YourProjectName/plugins/com.instabug.cordova.plugin/src/android/MyApplication.java
in your project. :blush:

**Comment by garyocampo** [comment]
Great!!!!! thank you so much for the quick response.
