### ISSUE TITLE
Issue with initialization in iOs

### ISSUE THREAD

**Issue by mpastorini** [Instabug/instabug-cordova#31]
Hi,

I'm getting this error
"Instabug could not be initialized - An application token must be provided."

After doing this 

```
cordova.plugins.instabug.activate(
  {
       ios: '0cca03baf6e1c178f776ddb594706196'
  },
  'shake',
  {
      commentRequired: true,
      colorTheme: 'dark'
  },
  function () {
      console.log('Instabug initialized.');
  },
  function (error) {
    console.log('Instabug could not be initialized - ' + error);
  }
);
```
I'm in the first instance of the installation, in the popup, so I took the token from this line

[Instabug startWithToken:@"0cca03baf6e1c178f776ddb594706196" invocationEvent:IBGInvocationEventShake];

Something of that lines could be wrong ? Or maybe I copied the token from the wrong place..
Besides I'm testing with an iPhone7 simulator, can be a problem with that ?

Thanks in advance.

**Comment by tomasnocetti** [comment]
Hi guys, we are in a big implementation of your software and we are having the same issue, Android is working but not IOS.

**Comment by salmatarzi** [comment]
Hi @mpastorini @tomasnocetti I know this issue has been here for a few days, I'm really sorry to keep you waiting, I will check this out and get back to you.

**Comment by salmatarzi** [comment]
@mpastorini @tomasnocetti Quick update: the fix is now done, and there's a PR created for it. Will update you again, when the release is out. #32

**Comment by salmatarzi** [comment]
@mpastorini @tomasnocetti The fix is now released, please update to the latest version. 😊
