### ISSUE TITLE
Error: Failed to fetch plugin https://github.com/DevHossamHassan/cordova-multidex via registry.

### ISSUE THREAD

**Issue by Malrok** [Instabug/instabug-cordova#37]
Hello,

I have installed the plugin on an Ionic 2.2.1 project using the npm command.
When adding the android platform I got the following error:

    Error: Failed to fetch plugin https://github.com/DevHossamHassan/cordova-multidex via registry.
    Probably this is either a connection problem, or plugin spec is incorrect.
    Check your connection and plugin name/version/URL.
    Failed to get absolute path to installed module

**Comment by Slavrix** [comment]
https://github.com/Instabug/instabug-cordova/issues/25
this might help

**Comment by reemalashry1** [comment]
@Malrok We are working on fixing the issue with npm, meanwhile, would you please install the plugin using: `cordova plugin add https://github.com/Instabug/instabug-cordova`

**Comment by Malrok** [comment]
Hi,
I've tried that, but the result is the same :(

**Comment by reemalashry1** [comment]
@Malrok Would you mind please sharing with me how did you install [here]?(https://github.com/Instabug/instabug-cordova/issues/38#issuecomment-333825006)

**Comment by bhawesh96** [comment]
I'm getting the same error. Can you please provide a fix?

**Comment by victorvicky** [comment]
I too get the same error.can you please provide a fix?

**Comment by victorvicky** [comment]
I have installed the plugin on an Ionic 3 project using the npm command.
When adding the android platform I got the following error:

Error: Failed to fetch plugin https://github.com/DevHossamHassan/cordova-multidex via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by anacesponda** [comment]
I'm getting the same error. Is there any solution?

**Comment by MattiaPrimavera** [comment]
+1

**Comment by Korazy** [comment]
Hi @MattiaPrimavera, @anacesponda, @victorvicky, @bhawesh96 

First off, please accept my apologies for the delay in our response. 

Can you please try using `cordova plugin add instabug-cordova -nofetch` and let me know if it works for you?

**Comment by anacesponda** [comment]
Hi @Korazy. I tried and it didn't work.

**Comment by christhompson05** [comment]
@Korazy the `--nofetch` flag was removed from cordova 8.0.0. Is there a different workaround?

**Comment by Korazy** [comment]
@anacesponda @christhompson05 thanks for getting back to us! We're checking now for the workaround.

**Comment by jverb** [comment]
@Korazy Any update on a fix or workaround for cordova 8.0.0 we could use? We still can't build our app with Instabug so we removed it and have been building without it for now so we can make releases 😞

**Comment by HeshamMegid** [comment]
This has been fixed in the latest release. Could you please give it a try and reopen the issue if the problem persists?
