### ISSUE TITLE
Automated Installation

### ISSUE THREAD

**Issue by monove** [Instabug/instabug-cordova#41]
Hi,

I used Instabug 2 years ago using the Cordova plugin created by @elizabethrego and I was notified when you guys created this plugin on your own.

To have to manually edit AndroidManifest file and replace stuff is very not Cordova style. In Cordova it is expected that at any given time, one can simply do a remove and add to a platform without any further work.

You guys should unify the activation of this plugin to look like this:
```
cordova.plugins.instabug.activate(
    {
        ios: 'MY_IOS_TOKEN',
        android: 'MY_ANDROID_TOKEN'
    },
    'shake',
    function () {
        console.log('Instabug initialized.');
    },
    function (error) {
        console.log('Instabug could not be initialized - ' + error);
    }
);
```
or if you need the token during the installation of the plugin do something like:
```
cordova plugin add https://github.com/Instabug/instabug-cordova --variable ANDROID_TOKEN="ewefwfefwefwsfeffqf"
```

**Comment by ZiadAyman** [comment]
Hey @monove 
I get your point, however android SDK needs to get initialized in the application class and cannot be initialized in an activity to avoid unexpected behaviors in the UI. We'll be checking this again from our side and I will keep you updated if there will be any changes :)

**Comment by monove** [comment]
Thanks for your prompt response.

There is an after_plugin_add event in Cordova where you can automate all of the custom work you're asking the user to remember to do. See https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/. There are tonz of plugins out there that add their own hooks.

**Comment by ZiadAyman** [comment]
@monove Apologies for the late reply this time :)

I communicated this with our cross-platform team and I will see what can they do and keep you posted.

**Comment by HeshamMegid** [comment]
@monove we've added this to our backlog and will be working on it in a future release.
