### ISSUE TITLE
No reports available

### ISSUE THREAD

**Issue by vbezruchkin** [Instabug/instabug-cordova#43]
Hi,

We've added your services to our ionic application. Added necessary key.
I see a notification when we start an application, and when we shake a device we get a report window.
Anyhow when we click report bug, nothing comes to our account.

Could you please advise if this is a common issue?

Here is the configuration we have:
```
$ node -v
v6.11.3

$ npm --version
5.5.1
```
We tried to update to a new version, no result as well so far.

Please advise. Thanks

**Comment by ZiadAyman** [comment]
Hey @vbezruchkin 
This is now communicated to our cross-platform team and I will be notifying you once this is reproduced from our side and fixed.

**Comment by ZiadAyman** [comment]
hey @vbezruchkin  
Can you tell me if this is happening on iOS and android? 
Also, do you succeed in reporting your bug and you get a message that you already reported it on the mobile? However the problem here is that you can never see the bug on your dashboard?

Is it the case?

**Comment by vbezruchkin** [comment]
Hello,

It's happening on our Android app. We now focus on android version only.

- when I open application, I can see a notice to shake
- when I shake an application I can see an instabug control to report
- when I report I get notice everything is fine, report sent 

But I don't see this report in my instabug account area.

Here is our ionic info:
```
cli packages: (C:\Users\webap\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.3
    npm  : 5.5.1
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by vbezruchkin** [comment]
@amalichev please join the discussion. Thanks

**Comment by amalichev** [comment]
Hello @ZiadAyman  

Please look at the screenshots below.

![screenshot_2017-12-28-11-47-43-461_at xapp pixo](https://user-images.githubusercontent.com/13551696/34401483-c3579e60-ebc5-11e7-855d-310064532aab.png)
![screenshot_2017-12-28-11-47-56-999_at xapp pixo](https://user-images.githubusercontent.com/13551696/34401485-c49ea070-ebc5-11e7-9051-5aa801476b9e.png)
![screenshot_2017-12-28-11-48-30-310_at xapp pixo](https://user-images.githubusercontent.com/13551696/34401487-c79566ba-ebc5-11e7-80cc-334377776929.png)
![screenshot_2017-12-28-11-48-36-041_at xapp pixo](https://user-images.githubusercontent.com/13551696/34401488-cd54fe58-ebc5-11e7-8231-3fcdea9c7db7.png)

**Comment by vbezruchkin** [comment]
And when we check it in the dashboard, we don't see any results. The key is correct, if we don't set the key - we don't even see any of these notices and cannot initialize instabug functionality.

Thanks

**Comment by ZiadAyman** [comment]
Hey @vbezruchkin 
I will need to get more details regarding your app like the token so we need to do this privately. 
Do you mind talking to me from Instabug's website or emailing us on contactus@instabug? 

I'll be taking it from there :)

**Comment by vbezruchkin** [comment]
Hi,

Thanks for your assistance, guy. Yes the issue has been resolve privately.

Cheers

**Comment by ZiadAyman** [comment]
Absolutely my pleasure @vbezruchkin 

Always get back please whenever you need any help :)

**Comment by juliansci** [comment]
@vbezruchkin Hi! How did resolve it? I have the same problem. Thanks!

**Comment by vbezruchkin** [comment]
Hi,

The guys from support made some changes for us, and advised to modify some code. Please get in touch with their support team, which is absolutely perfect.

Good luck.

**Comment by Korazy** [comment]
@vbezruchkin thank you so much for the compliment, it means a lot to us!

@juliansci please feel free to reach us directly from your dashboard or by emailing us on contactus@instabug.com. We would love to help you :)
