### ISSUE TITLE
Issues with Android and IOS

### ISSUE THREAD

**Issue by tomasnocetti** [Instabug/instabug-cordova#45]
Hello Instabug support team, im having the following error when executing ionic build in android

Node version: 4.4.2
Android Studio: 3.0.1
Cordova: 6.2.2

""""
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-v4:26.0.2.
     Searched in the following locations:
         file:/Users/gabi/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.0.2/support-v4-26.0.2.pom
         file:/Users/gabi/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.0.2/support-v4-26.0.2.jar
         file:/Users/gabi/workspace/frisum-app/project/platforms/android/sdk-manager/com/android/support/support-v4/26.0.2/support-v4-26.0.2.jar
     Required by:
         project :
   > Could not find com.android.support:support-v4:26.0.2.
     Searched in the following locations:
         file:/Users/gabi/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.0.2/support-v4-26.0.2.pom
         file:/Users/gabi/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.0.2/support-v4-26.0.2.jar
         file:/Users/gabi/workspace/frisum-app/project/platforms/android/sdk-manager/com/android/support/support-v4/26.0.2/support-v4-26.0.2.jar
     Required by:
         project : > com.journeyapps:zxing-android-embedded:3.3.0
         project : > com.android.support:appcompat-v7:23.1.0
   > Could not find com.android.support:support-v4:26.0.2.
     Searched in the following locations:
         file:/Users/gabi/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.0.2/support-v4-26.0.2.pom
         file:/Users/gabi/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/26.0.2/support-v4-26.0.2.jar
         file:/Users/gabi/workspace/frisum-app/project/platforms/android/sdk-manager/com/android/support/support-v4/26.0.2/support-v4-26.0.2.jar
     Required by:
         project : > com.instabug.library:instabug:4.6.1 > com.instabug.library:instabug-survey:4.6.1 > com.instabug.library:instabug-core:4.6.1
""""

I have tried uninstalling the Android Studio SDK support repository and letting the package being installed by itself but i have not gotten a solution.
Wait for your reply.

**Comment by MaFranceschi** [comment]
Hi! Did you solve this issue @tomasnocetti? there's a very similar issue related in their react native repository. You can follow the thread in here https://github.com/Instabug/instabug-reactnative/issues/148

**Comment by HeshamMegid** [comment]
Closing this for now since it's a very old issue. Please reopen/create a new issue if you're still having trouble.
