### ISSUE TITLE
issue with ionic 3

### ISSUE THREAD

**Issue by sujitgawas19** [Instabug/instabug-cordova#49]
Instabug plugin is not getting initialized.

Here is the code : 

document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
  onDeviceReady(){
    this.receivedEvent('deviceready');
    this.initInstabug();
  }

  initInstabug() {
    cordova.plugins.instabug.activate(
        {
            android: '44f3f69ce99ff14e4307b26558b09f72'
            // ios: 'IOS_TOKEN'
        },
        'button',
        {
            commentRequired: true,
            colorTheme: 'light',
            enableIntroDialog: false
        },
        () => {
            console.log('Instabug initialized.');
        },
        (error) => {
            console.log('Instabug could not be initialized - ' + error);
        }
    );
  }

Error : TypeError: Cannot read property 'instabug' of undefined

**Comment by sujitgawas19** [comment]
Sorry... my bad..
The plugin was not installed properly 
Now the plugin is installed and it is getting initialised but the ionic app crashes after plugin initialisation.
Can anyone help please??

**Comment by salmatarzi** [comment]
@sujitgawas19 Can you please share with me the error you're getting?

**Comment by sujitgawas19** [comment]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.healthwise.io/com.instabug.cordova.plugin.IBGPluginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.settings.b.e(boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by salmatarzi** [comment]
@sujitgawas19 Do you mind sharing all your Instabug code to be able to gain more context about the issue?

**Comment by sujitgawas19** [comment]
Here is all the code :  
onDeviceReady(){
    this.initInstabug();
  }  

initInstabug() {
    cordova.plugins.instabug.activate(
        {
            android: '44f3f69ce99ff14e4307b26558b09f72'
        },
        'button',
        {
            commentRequired: true,
            colorTheme: 'light',
            enableIntroDialog: false
        },
        () => {
            console.log('Instabug initialized.');
        },
        (error) => {
            console.log('Instabug could not be initialized - ' + error);
        }
    );
  }

I also changed the ANDROID_TOKEN in MyApplication.java file

**Comment by HeshamMegid** [comment]
@sujitgawas19 very sorry for super late reply! Unfortunately, we haven't been able to reproduce this.

If you haven't managed to get everything to work fine, please reopen this issue.
