### ISSUE TITLE
MAJOR: issues with 1.9 update and iOS

### ISSUE THREAD

**Issue by tmk1991** [Instabug/instabug-cordova#50]
ERROR ITMS-90087: "Unsupported Architectures. The executable for Link Your Fit.app/Frameworks/Instabug.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for Link Your Fit.app/Frameworks/InstabugCore.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'Link Your Fit.app/Frameworks/Instabug.framework/Instabug' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'Link Your Fit.app/Frameworks/InstabugCore.framework/InstabugCore' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

**Comment by salmatarzi** [comment]
@tmk1991 Can you make sure that there's a StripFrameworkScript in your Build Phases?

<img width="1401" alt="screen shot 2018-03-04 at 12 48 56" src="https://user-images.githubusercontent.com/10965023/36944749-10ad853a-1fab-11e8-9b8d-b8a50f485cb4.png">

**Comment by salmatarzi** [comment]
@tmk1991 No, this is not new to the 1.9.x release. Would it be possible to open the project in Xcode and check for that build phase script? I understand that nothing changed that should require you to do that, but we need it to be able to debug this particular issue.

**Comment by tmk1991** [comment]
Its showing  - Doesnt solve the issue since it builds with Ionic Pro Serverside
![image](https://user-images.githubusercontent.com/20258296/37493223-a499b926-287a-11e8-8b83-b8f2f30864ee.png)

**Comment by tmk1991** [comment]
When it installs into the cordova config.xml it's listed as: 
    <plugin name="com.instabug.cordova.plugin" spec="~1.0.0" />

**Comment by tmk1991** [comment]
When you run the install it adds this to the config.xml. Why is it putting in 1.0? Could this be the issue?
`    <plugin name="com.instabug.cordova.plugin" spec="~1.0.0" />
`

**Comment by tmk1991** [comment]
Any update? I can't advance my project using instabug
![image](https://user-images.githubusercontent.com/20258296/37807548-6d76ac0e-2e1c-11e8-8b28-1bd6e38214da.png)

**Comment by Korazy** [comment]
Hey @tmk1991 apologies for the late reply. Can you confirm if you get this error during building or archival?

**Comment by tmk1991** [comment]
@Korazy  - Thank you for the reply. 

It builds and archives into an ipa file however when it goes through uploading to apple validation it gives the errors I listed.

I can confirm by specifying the 1.8.2 version I do not have any issues. I would like to use the latest version but will be on 1.8.2 until this is resolved.

**Comment by tmk1991** [comment]
@Korazy  - Is this new to 1.9.1? Why would the 1.8.2 version work without any issues using the same build process?

**Comment by nymphetamineinside** [comment]
the same issue with 1.10.1

**Comment by tmk1991** [comment]
Stuck on 1.8.2 for now.  @Korazy  any update?

**Comment by Korazy** [comment]
@tmk1991 apologies for the late response as I was away due to illness. As @nymphetamineinside mentions, it does indeed seem that the resolution is to add the strip script manually as we are unsure why this started occurring only after 1.8.2. We are still investigating the issue.

**Comment by bterres** [comment]
@tmk1991 are you able to submit an app built with version 1.8.2 to iTunes Connect? I was able to **build** the app using 1.8.2 (thanks to your suggestion) and I can also install that app ad-hoc with a development cert, but submissions to iTunes Connect built with production certs still fail with the "Unsupported Architectures" error.

Just wondering if you've gotten an app with v1.8.2 all the way to the app store or if you are getting the same results that I am.

**Comment by tmk1991** [comment]
@bterres  Only with 1.8.2 am I able to get it in.

I use this in config xml:
`    <plugin name="com.instabug.cordova.plugin" spec="https://github.com/Instabug/instabug-cordova#v1.8.2" />
`
and this in package json -
`    "instabug-cordova": "1.8.2",
`

@Korazy  I hope you're feeling well. I can't inject anything into the build and packaging because its all handled in the cloud with ionic pro.

**Comment by tmk1991** [comment]
@Korazy  the issue is going onto 60 days. Any hope of resolution? 

Thanks!

**Comment by Korazy** [comment]
@tmk1991 actually we're currently working on a workaround for you, I will try to get back to you as soon as possible with. Please accept my sincerest apologies for this delay.

**Comment by tmk1991** [comment]
Thanks! We'll continue to use 1.8.2 until then.

**Comment by Korazy** [comment]
@tmk1991 can you please try doing the following:
1 - Make sure embed frameworks is above StripFrameworkScript
2 - Code sign on copy is ticked in embed frameworks
![image](https://user-images.githubusercontent.com/4321051/39471015-2fe7d612-4d41-11e8-86d1-4a2657af1c85.png)

You can also find a link to a sample project done in the same way [here](https://drive.google.com/file/d/1w-nTwIfduW9KdJz9ZngnjzTw5jh8Hzo-/view?usp=sharing). Just make sure to run `npm install` first, then you can run the app normally :)

**Comment by tmk1991** [comment]
Thank you. If I go through Xcode and do all of this it works as expected.  In 1.8.2 I never had to open xcode. Its not part of our build process.

**Comment by Korazy** [comment]
Unfortunately, sometimes some manual actions are required. Is everything working well for you now or are there still issues?
