### ISSUE TITLE
Hosting Versions on Github

### ISSUE THREAD

**Issue by tmk1991** [Instabug/instabug-cordova#51]
Need to host versions on github so we can modify our config.xml to point to the correct version we need.

**Comment by salmatarzi** [comment]
@tmk1991 Can you please elaborate more what you mean by hosting versions on Github?

**Comment by tmk1991** [comment]
In our config.xml we use:
    `<plugin name="com.instabug.cordova.plugin" spec="https://github.com/Instabug/instabug-cordova" />`

If you update your master branch, we cannot control which version of Instabug we use since it will pull from Master. 

You just updated to 1.9.x and we want to point back to 1.8.2 for instance. I've created another issue for the bugs related to the latest update.

**Comment by salmatarzi** [comment]
Yes, you can remove the plugin and add it again using: 
_**cordova plugin add https://github.com/Instabug/instabug-cordova#v1.8.2**_

**Comment by tmk1991** [comment]
> cordova plugin add https://github.com/Instabug/instabug-cordova#v1.9.1 --save
Installing "com.instabug.cordova.plugin" for ios

Failed to install 'com.instabug.cordova.plugin': CordovaError: Failed to fetch plugin https://github.com/DevHossamHassan/cordova-multidex via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

**Comment by tmk1991** [comment]
It looks like it doesn't install the script:
![image](https://user-images.githubusercontent.com/20258296/37631376-cd297df2-2bbf-11e8-80a8-fda0a3809460.png)
