### ISSUE TITLE
[Android] FileNotFoundException error while submitting bug

### ISSUE THREAD

**Issue by imVinayPandya** [Instabug/instabug-cordova#53]
I am using ionic cordova SDK of instabug. while i tried to send bug from mobile app using instabug its not sending bug to instabug web portal. i have tried to debug from android studio and found following error in log.

`W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.ransomlab.quarterly/files/instabug/attachments/bug_1525930433753_.jpg: open failed: ENOENT (No such file or directory)
                  at libcore.io.IoBridge.open(IoBridge.java:452)
                  at java.io.FileInputStream.<init>(FileInputStream.java:76)
                  at com.instabug.library.util.BitmapUtils.compressBitmapAndSave(BitmapUtils.java:94)
                  at com.instabug.bug.d.d(LiveBugManager.java:188)
                  at com.instabug.bug.d.c(LiveBugManager.java:132)
                  at com.instabug.bug.view.e.h(BugReportingFragmentPresenter.java:319)
                  at com.instabug.bug.view.c.onDoneButtonClicked(BugReportingFragment.java:380)
                  at com.instabug.library.core.ui.ToolbarFragment$1.onClick(ToolbarFragment.java:44)
                  at android.view.View.performClick(View.java:5212)
                  at android.view.View$PerformClick.run(View.java:21214)
                  at android.os.Handler.handleCallback(Handler.java:739)
                  at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:148)
                  at android.app.ActivityThread.main(ActivityThread.java:5541)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
              Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                  at libcore.io.Posix.open(Native Method)
                  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                  at libcore.io.IoBridge.open(IoBridge.java:438)`

here is my project configuration

**intabug cordova sdk version**

`com.instabug.cordova.plugin 1.0.0 "instabug-cordova"`

**ionic info**

cli packages: (/home/vinay/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.11.1
    npm               : 6.0.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/vinay/Android/Sdk

Misc:

    backend : pro

note: I have tried to give storage permission manually from my android settings. still it is not working.

**Comment by imVinayPandya** [comment]
okay, I will try and let you know about that.

Thank you for your response.

**Comment by Korazy** [comment]
Hey @imVinayPandya 

I hope you're well. Was the issue resolved for you?

**Comment by TaeHagen** [comment]
It appears I am experiencing this issue at the moment. Instabug says the bug submitted correctly, but no bug appears on the console. This is the logcat:

`W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.ratetheplate.app/files/instabug/attachments/bug_1548984641191_.jpg (No such file or directory)
W/System.err:     at java.io.FileInputStream.open0(Native Method)
W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
W/System.err:     at com.instabug.library.util.BitmapUtils$1.run(BitmapUtils.java:111)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at com.instabug.library.util.threading.b$1.run(PriorityThreadFactory.java:28)
W/System.err:     at java.lang.Thread.run(Thread.java:764) `

Using instabug-cordova: 8.0.6
Cordova CLI version: 8.1.2 (cordova-lib@8.1.1)
Using MacOS Mojave.
Had to force compileSdkVersion to be android-28 by using gradle.properties for instabug to compile.

Also, when starting the application, this occurs:
`W/System.err: org.json.JSONException: Value {"error":"Application not found"} of type org.json.JSONObject cannot be converted to JSONArray
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err:     at org.json.JSONArray.<init>(JSONArray.java:96)
W/System.err:     at org.json.JSONArray.<init>(JSONArray.java:108)
W/System.err:     at com.instabug.bug.view.actionList.service.a$1.a(ReportCategoriesServiceHelper.java:82)
W/System.err:     at com.instabug.bug.view.actionList.service.a$1.onNext(ReportCategoriesServiceHelper.java:55)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
W/System.err:     at com.instabug.library.network.NetworkManager$1.subscribe(NetworkManager.java:121)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12025)
W/System.err:     at com.instabug.bug.view.actionList.service.a.a(ReportCategoriesServiceHelper.java:55)
W/System.err:     at com.instabug.bug.view.actionList.service.ReportCategoriesService.a(ReportCategoriesService.java:47)
W/System.err:     at com.instabug.bug.view.actionList.service.ReportCategoriesService.runBackgroundTask(ReportCategoriesService.java:43)
W/System.err:     at com.instabug.library.network.a.onHandleWork(InstabugBackgroundService.java:28)
W/System.err:     at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
W/System.err:     at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)`

Your help is appreciated.

**Comment by TaeHagen** [comment]
I can confirm the issue is fixed when manually entering APP_TOKEN in `platforms/android/app/src/main/java/com/instabug/cordova/plugin/MyApplication.java`.
It seems plugins/instabug-cordova/src/android/MyApplication.java is not copying to `platforms/android/app/src/main/java/com/instabug/cordova/plugin/MyApplication.java`

**Comment by salmamali** [comment]
@TaeHagen 
The APP token needs to be added directly to the file in the path `platforms/android/app/src/main/java/com/instabug/cordova/plugin/MyApplication.java` since cordova copies the file in the path `plugins/instabug-cordova/src/android/MyApplication.java` only once on installation and therefore changing it after installation will not affect the file in the first path.
