### ISSUE TITLE
IBGScreenshotCapturer crash

### ISSUE THREAD

**Issue by kalliste** [Instabug/instabug-cordova#54]
Looks like I recently got a crash while taking a screenshot
[Crash#31.txt](https://github.com/Instabug/instabug-cordova/files/2051636/Crash.31.txt)

**Comment by Korazy** [comment]
Hey @kalliste 

Thanks for reporting this, would you be able to tell me which SDK version you're currently on?

**Comment by kalliste** [comment]
I would if I knew where to look for that information

**Comment by kalliste** [comment]
Ok. Got my hands on the build archive and found this in Instabug.h

 File:       Instabug/Instabug.h

 Contains:   API for using Instabug's SDK.

 Copyright:  (c) 2013-2018 by Instabug, Inc., all rights reserved.

 Version:    7.12.7

**Comment by Korazy** [comment]
Can you please update to the latest version and let me know if it resolves this bug?

**Comment by kalliste** [comment]
haven't seen it again recently
