### ISSUE TITLE
Not able to install the plugin

### ISSUE THREAD

**Issue by enestdharam** [Instabug/instabug-cordova#57]
cordova plugin add instabug.cordova@latest --save
✖ Running command - failed!
[ERROR] An error occurred while running cordova plugin add instabug.cordova@latest --save (exit code 1):

        Error: Failed to fetch plugin instabug.cordova@latest via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! code E404
        npm ERR! 404 Not Found: instabug.cordova@latest

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/pc50/.npm/_logs/2018-08-21T14_06_18_185Z-debug.log

Also

 cordova plugin add https://github.com/Instabug/instabug-cordova@latest --save
✖ Running command - failed!
[ERROR] An error occurred while running cordova plugin add https://github.com/Instabug/instabug-cordova@latest --save

        (exit code 1):

        Error: Failed to fetch plugin https://github.com/Instabug/instabug-cordova@latest via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! /usr/bin/git ls-remote -h -t https://github.com/Instabug/instabug-cordova%40latest.git
        npm ERR!
        npm ERR! fatal: unable to access 'https://github.com/Instabug/instabug-cordova%40latest.git/': The requested URL
        returned error: 400
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/pc50/.npm/_logs/2018-08-21T14_21_29_128Z-debug.log

**Comment by Korazy** [comment]
Hey @enestdharam 

Thanks for reaching out, can you try cordova plugin add instabug-cordova@8.0.3?

We use a - instead of a .

**Comment by Korazy** [comment]
Was the issue resolved for you?

**Comment by Korazy** [comment]
Please feel free to reopen this issue should you run into it again :)
