### ISSUE TITLE
Support for android@7.0.0 and higher

### ISSUE THREAD

**Issue by bellalMohamed** [Instabug/instabug-cordova#58]
There are major problems with installing instabug android SDK on projects running android@7.0.0 or higher, which is the path of the AndroidManifest.xml file.
you can reproduce the problem easily by creating a new ionic cordova project installing android@7.0.0 then try to build the app

**Comment by ramiimagdi** [comment]
Thank you for reach out to us @bellalMohamed.

Please allow me some time to investigate this issue further and get back to you as fast as possible.

**Comment by ramiimagdi** [comment]
Hello @bellalMohamed and @ahmedkhaled4d, I just wanted to let you know that we do support Cordova 7 on version v8.0.4. 

You  will have to remove the plugin and add it again using the following command:
``` cordova plugin remove instabug-cordova
cordova plugin add instabug-cordova ```

Please feel free to get back to us if you have any questions at all.

**Comment by ramiimagdi** [comment]
Hello again,

Please don't hesitate to reopen this thread or to reach out to us if you have any sort of difficulties. 

Have a great day!
