### ISSUE TITLE
Issue with android@7.0.0 and higher.

### ISSUE THREAD

**Issue by bellalMohamed** [Instabug/instabug-cordova#59]
The issue #58 is stilll not solved, you can check the build.gradle file you'll see the path of the AndroidManifest.xml is still wrong, I've to manually change it to fix the build problem, please try to install the package to reproduce the issue.

**Comment by rdiaa** [comment]
Hello, @bellalMohamed I'm so sorry that you are still facing the issue. I will check it form my side and get back to you shortly.

**Comment by rdiaa** [comment]
Hello, @bellalMohamed  Let me please clarify to you why is this happening, when you install the package, it's installed with the old path, you  need to have Cordiva-Android 7 installed and then after you follow the steps below:
cordova plugin remove instabug-cordova
cordova plugin add instabug-cordova
 you will need to remove instabug and re-install it again. This will update the new path.

Please let me know if anything is unclear

**Comment by rdiaa** [comment]
@bellalMohamed  I will be waiting for your feedback

**Comment by rdiaa** [comment]
@bellalMohamed I want to check if everything is working smoothly now after you re-installed Instabug

**Comment by rdiaa** [comment]
@bellalMohamed Please get back to us if you need any help.
