### ISSUE TITLE
Ionic 3 Android Platform build fails

### ISSUE THREAD

**Issue by MyC-Greg** [Instabug/instabug-cordova#63]
Hi,

I can't run the build (--prod --release) process for the Android Platform:

> FAILURE: Build failed with an exception.

My system:
`"ionic-angular": "3.9.2"`
 `"instabug-cordova": "^8.0.6"`

The output of the terminal:

> * Where:
> Script .../platforms/android/instabug-cordova/myApp-build.gradle' line: 24
> 
> * What went wrong:
> A problem occurred evaluating script.
> > Could not find method implementation() for arguments [com.instabug.library:instabug:8.0.12] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 

> [ERROR] An error occurred while running subprocess cordova.

I installed the plugin with the ionic command 

> ionic cordova plugin add instabug-cordova

Any idea on how to solve this? Thanks a lot!

**Comment by salmamali** [comment]
@MyC-Greg 
Your gradle version is outdated, you need to use at least gradle 3.4 to be able to use Instabug. In the path `<project>/platforms/android/build.gradle` update as follows: 
```
classpath 'com.android.tools.build:gradle:3.3.1'
```

**Comment by MyC-Greg** [comment]
@salmamali 
Thanks! That was indeed the plugin which was causing this error. But now that the plugin is updated, the app builds perfectly without the instabug-cordova plugin but gives me an error with it:

> BUILD FAILED in 8s
> Error: /Users/gregoirenedelec/documents/myc/code/mycharlotteapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':processReleaseResources'.
> > Android resource linking failed
>   /xx/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/ad47f1db181fc8cc6a8e986bba2b4ae2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
>       
>   /myApp/platforms/android/build/intermediates/incremental/mergeReleaseResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
>       
>   /xx/.gradle/caches/transforms-1/files-1.1/design-28.0.0.aar/07d74246317d5d6350534dc2646ef538/res/values/values.xml:161:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.
>       
>   /xx/.gradle/caches/transforms-1/files-1.1/design-28.0.0.aar/07d74246317d5d6350534dc2646ef538/res/values/values.xml:161:5-202: AAPT: error: resource android:attr/ttcIndex not found.
>       
>   error: failed linking references.
> 

From what I found on SO, it could be related to the SdkVersion. 
[https://stackoverflow.com/questions/49280632/error9-5-error-resource-androidattr-dialogcornerradius-not-found]
I tried several solutions like this:
[https://developer.android.com/studio/build/multidex]

In my GradleBuilder.js I have this line:
`  var SYSTEM_LIBRARY_MAPPINGS = [
        [/^\/?extras\/android\/support\/(.*)$/, 'com.android.support:support-$1:+'],...]`
Could that be the cause for an SdkVersion mismatch?

Any thought would be welcome.

**Comment by salmamali** [comment]
@MyC-Greg  Yes it is. You need to update your target sdk version to v28. You can do that by opening the file in the path `<project>/platforms/android/project.properties` and changing the target as follows
```
target=android-28
```

**Comment by MyC-Greg** [comment]
Great ! That works! Thanks!
