### ISSUE TITLE
Instabug failed to recognize header file

### ISSUE THREAD

**Issue by shaharpan2912** [Instabug/instabug-cordova#64]
Please review below screen shot.

I have installed instabug 8.0.7 plugin to my ionic app.

It does not recognize header file "IBGBugReporting.h" but it recognize "Instabug.h" from same folder/namespace

Please review below screen shot

![screen shot 2019-02-27 at 4 28 40 pm](https://user-images.githubusercontent.com/31267622/53485750-0b02d900-3aad-11e9-865e-ca43b78a229d.png)

**Comment by salmamali** [comment]
@shaharpan2912 We can't seem to reproduce this issue. And from your screenshot it looks like the header file `IBGBugReporting.h` exists in the Instabug framework. Could you try cleaning and rebuilding your project?

**Comment by shaharpan2912** [comment]
@salmamali I have tried many times. 
also try with removing plugin and adding it again.

**Comment by salmamali** [comment]
@shaharpan2912 What version of Instabug were you upgrading from?

**Comment by shaharpan2912** [comment]
@salmamali 8.0.4 and xcode version is 9.2

**Comment by HeshamMegid** [comment]
@shaharpan2912 would you mind updating to the latest version of Xcode and trying this again?

**Comment by HeshamMegid** [comment]
@shaharpan2912 closing this issue since we haven't heard back from you. Please feel free to reopen if you still need help.
