### ISSUE TITLE
[IOS] Adding Script Build Phase by zStripScript.js

### ISSUE THREAD

**Issue by nymphetamineinside** [Instabug/instabug-cordova#66]
Hello guys,

It seems i fixed your issue. Before that i had to add script build phase manually.

zStripScript.js works only in that case:

    fs.chmod(projectPath, '0755', function(exc) {
      fs.writeFileSync(projectPath, myProj.writeSync());
    });

**Comment by HeshamMegid** [comment]
Thanks, @nymphetamineinside. We'll test this to make sure it has no unintended side effects and include it in the next release.

**Comment by HeshamMegid** [comment]
While testing, we weren't able to reproduce the issue that this is attempting to solve. Do you have any more details that would help us reproduce it?

**Comment by nymphetamineinside** [comment]
I use ionic 2.2.3 and cordova 8

I build app for ios following way:
ionic state reset
ionic prepare ios

First thing is `ionic state reset` doesn't execute hooks like `after_plugin_install` you're using for adding build phase. But I live with that. It isn't an issue.

Issue can be reproduced by just adding plugin with `cordova plugin add`
The root cause is: you doesn't have enough permissions to change `project1/platforms/ios/Rogue.xcodeproj/project.pbxproj`

**Comment by salmamali** [comment]
@nymphetamineinside Would it be possible for you to update the Instabug plugin to the latest version, 8.2.0, and update cordova to 9 as well and see if the issue still happens?

**Comment by nymphetamineinside** [comment]
I already have your plugin 8.1.0 (updated a week ago with hope that that issue is fixed, but had to investigate and fix myself). I don't think I can update cordova to 9 now due to lack of time.

**Comment by igoris** [comment]
It looks like after incorporating this change the project file is written twice: 
``` 
fs.chmod(projectPath, '0755', function(exc) {
        fs.writeFileSync(projectPath, myProj.writeSync());
});
    
fs.writeFileSync(projectPath, myProj.writeSync());
```
I'm not sure why this change is really needed. So far this is the only plugin I saw that silently changes the permissions of the project file allowing anyone to read it.

Also, the script doesn't work in the case when the plugin is already added to the config.xml but the `platforms/` and `plugins/` folders are empty (e.g. after checkout on the CI server) and I need to re-generate the platform files by running `ionic cordova platform add ios`. For some reason the project file is not properly saved and as a result the phase is not added. Changing hook type to `after_platform_add` fixes this.
