### ISSUE TITLE
[ANDROID] Screenshot crashes my app

### ISSUE THREAD

**Issue by Galiza** [Instabug/instabug-cordova#68]
After SHAKING the screen, click on Report Bug, Take Screenshot, after submitting the screenshot, the entire app crashes, and afterwards keep on crashing, I need to re-install my app for it to work again.

**Comment by alyezz** [comment]
Thanks for reporting this, can you please send us the full stack trace? Thanks

**Comment by Galiza** [comment]
Hi @alyezz, yesterday I updated our Android version from 6.4.0 to 7.1.4 and the it stopped crashing.
