### ISSUE TITLE
Not showing any options on shaking device.

### ISSUE THREAD

**Issue by tarun57** [Instabug/instabug-cordova#78]
Hi i'm using ionic 3 i was added this plugin in my ionic project after run this on android when i'm shaking device it was not showing any options like 
"Talk to me"
"Report a problem"
Means to say i'm not able to report for any problem.

**Comment by alyezz** [comment]
@tarun57 can you please share with us your integration code?

**Comment by tarun57** [comment]
I was add plugin by cordova command 
"ionic cordova plugin add instabug-cordova"
Then add access token(replace "myapplication" with access token) in myapplication.java file in pluign.

**Comment by alyezz** [comment]
@tarun57 Please follow the steps here https://github.com/Instabug/instabug-cordova#installation

The MyApplication class integration code is no longer required.

**Comment by tarun57** [comment]
@alyezz  can you please describe me first step which js file i have only ts files.
