### ISSUE TITLE
[ERROR] Can't build after adding plugin

### ISSUE THREAD

**Issue by Galiza** [Instabug/instabug-cordova#81]
Following Cordova documentation to install the latest version of the plugin, I can't build the project anymore.

Here's the screenshot of the error:
![instabug](https://user-images.githubusercontent.com/9288512/64567369-79630680-d32e-11e9-82af-4feb50eab809.png)

**Comment by Edmu** [comment]
also android fails to be built: 

BUILD FAILED in 31s
.../platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: .../platforms/android/app/src/main/java/com/instabug/cordova/plugin/IBGPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Cannot fit requested classes in a single dex file (# methods: 78327 > 65536)
FAILURE: Build failed with an exception.

**Comment by AliAbdelfattah** [comment]
Hi @Edmu, this seems like a different issue. Please open a new issue (and fill out the template) to be able to help you.

**Comment by Edmu** [comment]
@AliAbdelfattah 

#85 

What template? Can't find any.

**Comment by AliAbdelfattah** [comment]
Hi @Galiza this should be fixed on our next Cordova release this week.

**Comment by AliAbdelfattah** [comment]
Closing this as the fix has been released a while ago.
