### ISSUE TITLE
Incorrect use of the "let" keyword causes an error with the old devices

### ISSUE THREAD

**Issue by SonoIo** [Instabug/instabug-cordova#82]
The following code throws an error on old devices that does not support let, const, etc...

https://github.com/Instabug/instabug-cordova/blob/ea8bddcea59a85e973dade0cbcca87e2088c8de0/www/bugReporting.js#L108-L110

Could you declare the variable `i` using "var" instead of "let"?

**Comment by AliAbdelfattah** [comment]
Hi @SonoIo, sorry for the late reply. We're looking into that.

**Comment by AliAbdelfattah** [comment]
Fix has been implemented and will be shipped with the next release.

**Comment by alyezz** [comment]
@SonoIo this issue has been fixed and is included in out latest release 9.1.6
