### ISSUE TITLE
android build fails after adding plugin

### ISSUE THREAD

**Issue by Edmu** [Instabug/instabug-cordova#85]
also fails to be build on android:

BUILD FAILED in 31s
.../platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: .../platforms/android/app/src/main/java/com/instabug/cordova/plugin/IBGPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Cannot fit requested classes in a single dex file (# methods: 78327 > 65536)
FAILURE: Build failed with an exception.

**Comment by AliAbdelfattah** [comment]
Hi @Edmu this is an android issue. Please enable multidex to fix it.

**Comment by Edmu** [comment]
@AliAbdelfattah thanks

installing `cordova-plugin-enable-multidex` helped - this could be included into documentation.
