### ISSUE TITLE
Customize text in UI

### ISSUE THREAD

**Issue by philippmayrth** [Instabug/Instabug-Cordova#87]
I could not find a way to access the text customization functionality from the Cordova plugin neither from the documentation (- https://docs.instabug.com/docs/cordova-locale) nor from digging around in the source code.

This is a functionality which exists in the iOS and Android documentation:
- https://docs.instabug.com/docs/ios-locale#section-overriding-string-values
- https://docs.instabug.com/docs/android-locale

Will this be supported at some point in the future?

**Comment by AliAbdelfattah** [comment]
@philippmayrth Yes, it should be supported soon. I'll keep this issue open for any updates regarding this API.

**Comment by philippmayrth** [comment]
@AliAbdelfattah is there any progress on this one?

**Comment by AliAbdelfattah** [comment]
@philippmayrth sorry for the late reply, this is now added in our latest release.
