### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by philippmayrth** [Instabug/instabug-cordova#88]
We were using this plugin with `^8.2.1` which should have updated only to minor versions which by convention can't include breaking changes but it still broke on Android (still working on iOS).
Only by changing to `8.2.1` without the caret we got rid of that bug.

**Comment by AliAbdelfattah** [comment]
Hi @philippmayrth, we're sorry to hear that. We try our best to follow these conventions and we definitely do not intend to break it. Would you mind sharing with us the bug or the cause of breaking so I could investigate it further and to avoid the likes of it in the future? We'd really appreciate it!

**Comment by philippmayrth** [comment]
Unfortunately not, I could get a debugger to attach to the Android App. This has something to do with how we setup the development environment.
I had to checkout older git commits of known working states and as those did not work either I knew it had to do with an update of this plugin.
Sorry I would rely like to provide more useful info here.

What I do know is that the issue was present on 5. Dezember while it did still work on the 19. November so whatever happened it had to be between those two dates.

**Comment by AliAbdelfattah** [comment]
No worries, thanks for the info anyway. We'll try to investigate further from our side and we'll do our best to avoid this from happening again.
