### ISSUE TITLE
Black screenshot screen in Android

### ISSUE THREAD

**Issue by SoldierCorp** [Instabug/instabug-cordova#9]
Hi,

I'm having an issue related to the build for Android devices because the screenshot is always black and only is showing the statusbar, do you know what causes this problem?

iOS works perfectly.

https://s3.amazonaws.com/instabug-pro/attachments/states/48962091/1b0dcaef7b6e5ad24993e5c3c1c0c9e7_one_bug_thumb/15763783/bug_1486497619423_.jpg?1486497762

**Comment by dherby** [comment]
Same issue here ! Ionic 2.0

**Comment by DevHossamHassan** [comment]
Hello @SoldierCorp and @dherby,
Thank you for reporting this issue.
We have shipped a fix for that issue in version 1.1.0, So please upgrade to the latest version and let me know if the issue still exists or not?

**Comment by samianc** [comment]
Hi @DevHossamHassan.
We've made an upgrade to v1.1.0 and the issue still there.

**Comment by salmatarzi** [comment]
Hi there @SoldierCorp, @dherby , and @samianc Is the issue you are facing still there?

**Comment by asadwaheed1** [comment]
@salmatarzi yes i am also facing black screenshot issue in android. When camera preview is running and html tags over it. It captures camera preview as black solid color and html tags over it

**Comment by salmatarzi** [comment]
@asadwaheed1 Are you using Crosswalk Webview or Service Webview?

**Comment by asadwaheed1** [comment]
Sorry I posted comment on wrong library. I needed to post on ionic-native/screenshot library.

**Comment by salmatarzi** [comment]
I will close this issue for now, if the problem still persists, feel free to re-open it.
