### ISSUE TITLE
Version disparity inquiry

### ISSUE THREAD

**Issue by zmart-sen** [Instabug/instabug-cordova#94]
If we look at the version listed in https://github.com/Instabug/instabug-cordova/blob/master/plugin.xml we see that it is well-behind the current 9.1.0 version. This is potentially an issue because `cordova plugin ls` (as of cordova -v: 9.00 at least) uses the version from plugin.xml and can lead to confusion.

Any chance for an explanation as to why this wouldn't be updated?

**Comment by AliAbdelfattah** [comment]
@zmart-sen thank you for reporting this. The fix has been implemented and will be shipped with the upcoming release.

**Comment by alyezz** [comment]
@zmart-sen  this issue has been fixed and is included in out latest release 9.1.6
