### ISSUE TITLE
Screen recorder is not working in Ionic IOS!

### ISSUE THREAD

**Issue by 08Thug** [Instabug/instabug-cordova#99]
After initializing Instabug i am currently using version-8.6.5 screen recorder is working fine in android but while in IOS after choosing the option take a screenrecoder the instabug closes automatically and can't even call instabug again by shaking the device.It can be called only after by reopening my application.

**Comment by alyezz** [comment]
@08Thug you need to add the following code to your app's `info.plist` to allow permission, more info here : https://docs.instabug.com/docs/ios-integration#managing-permissions

```	<key>NSMicrophoneUsageDescription</key>
	<string>*YOUR APP* needs access to your microphone so you can attach voice notes.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>YOUR APP* needs access to your photo library so you can attach images.</string>```

**Comment by 08Thug** [comment]
@alyezz let me try and get back to you! thank you
